#!/usr/bin/env node
/**
 * gen-keys.mjs — generate the RbxSync license-signing Ed25519 keypair.
 *
 * Run LOCALLY by the maintainer:
 *     node licensing/scripts/gen-keys.mjs
 *
 * What it does:
 *   - Generates a fresh Ed25519 keypair.
 *   - Writes the PUBLIC key (safe to commit) to:
 *       licensing/keys/public-key.txt   (base64 of the raw 32 public bytes)
 *       licensing/keys/public-key.rs     (ready-to-paste Rust const for the CLI)
 *   - PRINTS the PRIVATE key + the exact `wrangler secret put` command to YOUR
 *     TERMINAL ONLY. The private key is NEVER written to any file.
 *
 * SECURITY: the private key is printed once. Paste it straight into
 * `wrangler secret put LICENSE_SIGNING_PRIVATE_KEY` and do not save it anywhere
 * else. If you lose it, generate a new keypair and re-ship the CLI with the new
 * public key (old licenses stop verifying).
 */

import { webcrypto } from "node:crypto";
import { writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const { subtle } = webcrypto;
const here = dirname(fileURLToPath(import.meta.url));
const keysDir = join(here, "..", "keys");

function toB64(bytes) {
  return Buffer.from(bytes).toString("base64");
}

async function main() {
  const keyPair = await subtle.generateKey({ name: "Ed25519" }, true, [
    "sign",
    "verify",
  ]);

  // Private key → PKCS8 DER → base64. This is the value of the secret the Worker reads.
  const pkcs8 = new Uint8Array(await subtle.exportKey("pkcs8", keyPair.privateKey));
  const privB64 = toB64(pkcs8);

  // Public key → raw 32 bytes. This is what the CLI embeds and verifies against.
  const rawPub = new Uint8Array(await subtle.exportKey("raw", keyPair.publicKey));
  const pubB64 = toB64(rawPub);

  mkdirSync(keysDir, { recursive: true });

  // public-key.txt — base64 of the raw 32 public-key bytes.
  writeFileSync(join(keysDir, "public-key.txt"), pubB64 + "\n");

  // public-key.rs — a Rust snippet for the CLI to embed.
  const rustBytes = Array.from(rawPub).join(", ");
  const rustSnippet = `// RbxSync license public key — generated by licensing/scripts/gen-keys.mjs
// Verify license tokens against this key with ed25519-dalek's VerifyingKey::from_bytes.
// Base64 (raw 32 bytes): ${pubB64}
pub const LICENSE_PUBLIC_KEY: [u8; 32] = [${rustBytes}];
`;
  writeFileSync(join(keysDir, "public-key.rs"), rustSnippet);

  // ─── Print to terminal ONLY ────────────────────────────────────────────────
  const line = "─".repeat(72);
  process.stdout.write(`
${line}
  RbxSync license keypair generated.
${line}

  PUBLIC key written to (safe to commit):
    licensing/keys/public-key.txt
    licensing/keys/public-key.rs   ← paste into the Rust CLI

  Public key (base64, raw 32 bytes):
    ${pubB64}

${line}
  PRIVATE key — DO NOT COMMIT, DO NOT SAVE TO A FILE.
  Set it as the Worker secret by running this, then paste the value below:
${line}

    cd licensing && wrangler secret put LICENSE_SIGNING_PRIVATE_KEY

  When prompted, paste EXACTLY this value:

    ${privB64}

${line}
  For local dev, put the SAME value in licensing/.dev.vars (gitignored):
    LICENSE_SIGNING_PRIVATE_KEY=${privB64}
${line}
`);
}

main().catch((err) => {
  console.error("gen-keys failed:", err);
  process.exit(1);
});
